version: '2.1'
services:
  server:
    image: tfs:0.1v
    ports:
      - 7171:7171
      - 7172:7172
    restart: always
    depends_on:
            db:
                condition: service_healthy
#  gesior:
#    image: gesior:latest
#    restart: always
#    ports:
#      - 8080:80
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'forgottenserver'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'forgottenserver'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'test'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", 'mysql --database=forgottenserver --user=root --password=password --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
      interval: 30s
      timeout: 10s
      retries: 4
